# --------------------------------------------------------------
# led.py
# Generates a PowerPoint deck about LEDs.
# --------------------------------------------------------------
# 1️⃣  Install the required library (run once):
#     pip install python-pptx
#     (You can run this command directly from VS Code's terminal.)
from pptx import Presentation
from pptx.util import Pt
from pptx.dml.color import RGBColor

# ------------------------------------------------------------------
# Helper: add a slide with a title and a bulleted list
# ------------------------------------------------------------------
def add_bulleted_slide(prs, title_text, bullet_items):
    """Create a slide with a title and a bullet list."""
    # Use layout 1 = Title & Content
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)

    # Title
    slide.shapes.title.text = title_text

    # Content placeholder (bulleted list)
    tf = slide.placeholders[1].text_frame

    for i, txt in enumerate(bullet_items):
        # First paragraph already exists; subsequent ones need to be added
        p = tf.paragraphs[i] if i < len(tf.paragraphs) else tf.add_paragraph()
        p.text = txt
        p.level = 0
        p.font.size = Pt(18)
        p.font.name = "Calibri"
        p.font.color.rgb = RGBColor(0, 0, 0)

# ------------------------------------------------------------------
# Slide data: (title, [bullets...])
# ------------------------------------------------------------------
slides = [
    ("What is an LED?",
     ["Semiconductor device that emits light when forward-biased",
      "Invented 1962 (Nick Holonyak)",
      "Works via electroluminescence"]),

    ("How LEDs Work",
     ["P-type & N-type layers form a PN junction",
      "Electrons recombine with holes -> photons released",
      "Wavelength (color) -> band-gap energy"]),

    ("Key Characteristics",
     ["Efficiency: 20-200 lm/W (vs. incandescent ~15 lm/W)",
      "Longevity: 25,000-100,000 h",
      "Fast switching: ns-range",
      "Small size & robust"]),

    ("LED Colors & Materials",
     ["Red - AlGaAs",
      "Green - InGaN",
      "Blue - InGaN (high band-gap)",
      "White - Blue LED + phosphor or RGB mixing"]),

    ("Advantages Over Traditional Light Sources",
     ["Lower power consumption",
      "No warm-up time",
      "Shock-resistant",
      "Directional light -> less optics needed"]),

    ("Common Applications",
     ["Lighting: home, street, automotive, horticulture",
      "Displays: TVs, monitors, billboards, AR/VR",
      "Indicators: appliances, wearables, IoT devices",
      "Communications: Li-Fi, fiber-optic links"]),

    ("LED Packaging & Types",
     ["Through-hole (T-1 3/4, 5 mm) - classic indicator",
      "Surface-mount (SMD, 0805, 1206) - PCB integration",
      "Chip-on-Board (COB) - high-density arrays",
      "Flexible / OLED - bendable lighting"]),

    ("Design Considerations",
     ["Forward voltage (Vf): 1.8 V (red) -> 3.6 V (blue)",
      "Current limiting: resistors or constant-current drivers",
      "Thermal management: heat-sinks, copper pours",
      "Color Rendering Index (CRI) importance for indoor lighting"]),

    ("Future Trends",
     ["Micro-LED displays - high brightness, low power",
      "Smart/Connected LEDs - IoT integration, tunable color",
      "Improved phosphors - higher CRI, lower blue-hazard",
      "Sustainable manufacturing - recycling, eco-friendly materials"]),

    ("Summary",
     ["LEDs are energy-efficient, long-lasting light sources",
      "Wide range of colors & form factors",
      "Continuously evolving for smarter, greener lighting solutions"]),

    ("References",
     ["LEDs: Fundamentals, Materials, and Devices - B. O'Regan",
      "IEEE Spectrum - \"The LED Revolution\" (2023)",
      "https://www.ieee.org/led-resources",
      "Manufacturer datasheets (Cree, Osram, Nichia)"])
]

def create_presentation():
    prs = Presentation()

    # Add a title slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Light-Emitting Diodes (LEDs)"
    subtitle.text = "An Overview of LED Technology\nGenerated by Aura AI"

    # Add content slides
    for title_text, bullets in slides:
        add_bulleted_slide(prs, title_text, bullets)

    # Save the presentation
    output_filename = "LED_Presentation.pptx"
    prs.save(output_filename)
    print(f"Presentation saved as {output_filename}")

if __name__ == "__main__":
    create_presentation()