f = "src/desktop/native/capability_registry.py"
with open(f, "r", encoding="utf-8") as fh:
    lines = fh.readlines()

new_lines = []
new_lines.append('    def _register_clipboard_capabilities(self) -> None:\n')
new_lines.append('        """Register clipboard capabilities - full clipboard surface"""\n')
new_lines.append('        # Text operations\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.read_text",\n')
new_lines.append('            description="Read plain text from the clipboard",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.READ,\n')
new_lines.append('            permission_label="Read",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            usage_examples=["Get clipboard text", "Read copied text", "Paste clipboard"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.write_text",\n')
new_lines.append('            description="Write plain text to the clipboard",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.WRITE,\n')
new_lines.append('            permission_label="Write",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            events_triggered=["clipboard_changed"],\n')
new_lines.append('            usage_examples=["Copy text to clipboard", "Set clipboard content"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.clear",\n')
new_lines.append('            description="Clear the clipboard contents",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.WRITE,\n')
new_lines.append('            permission_label="Write",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            events_triggered=["clipboard_changed"],\n')
new_lines.append('            usage_examples=["Clear clipboard", "Empty clipboard"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        # Image operations\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.read_image",\n')
new_lines.append('            description="Read image from the clipboard - Windows bitmap",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.READ,\n')
new_lines.append('            permission_label="Read",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            usage_examples=["Get clipboard image", "Read screenshot"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.write_image",\n')
new_lines.append('            description="Write image to the clipboard - Windows bitmap",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.WRITE,\n')
new_lines.append('            permission_label="Write",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            events_triggered=["clipboard_changed"],\n')
new_lines.append('            usage_examples=["Copy image to clipboard", "Set clipboard image"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        # File operations\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.read_files",\n')
new_lines.append('            description="Read file paths from the clipboard",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.READ,\n')
new_lines.append('            permission_label="Read",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            usage_examples=["Get copied files", "Read file paths from clipboard"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.write_files",\n')
new_lines.append('            description="Write file paths to the clipboard",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.WRITE,\n')
new_lines.append('            permission_label="Write",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            events_triggered=["clipboard_changed"],\n')
new_lines.append('            usage_examples=["Copy files to clipboard", "Set clipboard files"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        # HTML operations\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.read_html",\n')
new_lines.append('            description="Read HTML content from the clipboard",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.READ,\n')
new_lines.append('            permission_label="Read",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            usage_examples=["Get clipboard HTML", "Read formatted content"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.write_html",\n')
new_lines.append('            description="Write HTML content to the clipboard",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.WRITE,\n')
new_lines.append('            permission_label="Write",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            events_triggered=["clipboard_changed"],\n')
new_lines.append('            usage_examples=["Copy HTML to clipboard", "Set clipboard HTML"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        # Format queries\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.get_formats",\n')
new_lines.append('            description="Get list of available clipboard formats",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.READ,\n')
new_lines.append('            permission_label="Read",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            usage_examples=["List clipboard formats", "What is in the clipboard"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.has_text",\n')
new_lines.append('            description="Check if clipboard contains text",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.READ,\n')
new_lines.append('            permission_label="Read",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            usage_examples=["Does clipboard have text", "Check clipboard content"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.has_image",\n')
new_lines.append('            description="Check if clipboard contains an image",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.READ,\n')
new_lines.append('            permission_label="Read",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            usage_examples=["Does clipboard have an image", "Check clipboard for image"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')
new_lines.append('        self.register(CapabilityDescriptor(\n')
new_lines.append('            name="clipboard.has_files",\n')
new_lines.append('            description="Check if clipboard contains files",\n')
new_lines.append('            manager="clipboard",\n')
new_lines.append('            category="clipboard",\n')
new_lines.append('            permission=PermissionRequired.READ,\n')
new_lines.append('            permission_label="Read",\n')
new_lines.append('            risk_level=RiskLevel.SAFE,\n')
new_lines.append('            supports_undo=False,\n')
new_lines.append('            usage_examples=["Does clipboard have files", "Check clipboard for files"],\n')
new_lines.append('        ))\n')
new_lines.append('\n')

result = lines[:248] + new_lines + lines[288:]
with open(f, "w", encoding="utf-8") as fh:
    fh.writelines(result)
print("SUCCESS")
