"""
Unified Artifact Store Model
Location: src/core/orchestration/artifact.py

Standardized Artifact model generated by backends and consumed by GUI / storage systems.
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass
class Artifact:
    """
    Universal Artifact model representing files, patches, reports, screenshots, etc.
    """

    artifact_id: str = field(default_factory=lambda: f"art_{uuid.uuid4().hex[:8]}")
    artifact_type: str = (
        "file"  # markdown, python_file, patch, git_commit, screenshot, pdf
    )
    location: str = ""  # File path or URI
    mime_type: str = "text/plain"
    creator: str = "unknown"  # Backend or Planner name
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "artifact_id": self.artifact_id,
            "artifact_type": self.artifact_type,
            "location": self.location,
            "mime_type": self.mime_type,
            "creator": self.creator,
            "created_at": self.created_at,
            "metadata": self.metadata,
        }
