"""
Unified Artifact Store Model
Location: src/core/orchestration/artifact.py

Standardized Artifact model generated by backends and consumed by downstream
DAG stages, GUI, and storage systems.

Every artifact carries a **content payload** — the actual data produced by an
upstream task (research text, markdown document, file bytes, etc.).  Downstream
tasks consume artifacts by reading their ``content`` field; metadata alone is
never sufficient to continue a pipeline.
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


@dataclass(frozen=True)
class VerificationReport:
    """
    Structured outcome of artifact verification checks.
    """

    success: bool = True
    checks: dict[str, bool] = field(default_factory=dict)
    confidence: float = 1.0
    observations: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "checks": self.checks,
            "confidence": self.confidence,
            "observations": self.observations,
        }


@dataclass(frozen=True)
class Artifact:
    """
    Universal Artifact model representing research results, documents, files,
    patches, screenshots, etc.

    Key design rule: every artifact that is produced by a DAG stage **must**
    carry a non-empty ``content`` payload.  Downstream stages validate this
    via ``has_payload`` before consuming the artifact.
    """

    artifact_id: str = field(default_factory=lambda: f"art_{uuid.uuid4().hex[:8]}")
    artifact_type: str = (
        "file"  # research, markdown, file, python_file, patch, screenshot, pdf
    )
    content: str = ""  # ← THE PAYLOAD — actual data produced by the upstream task
    location: str = ""  # File path or URI (populated after persistence)
    mime_type: str = "text/plain"
    creator: str = "unknown"  # Backend or Planner name
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    citations: list[str] = field(default_factory=list)  # Source URLs, references
    metadata: dict[str, Any] = field(default_factory=dict)

    # First-class resource fields for the AI Operating System
    session_id: str = ""
    owner: str = "aura"
    tags: list[str] = field(default_factory=list)
    verification_report: VerificationReport | None = None

    @property
    def has_payload(self) -> bool:
        """Return True if this artifact carries a non-empty string content payload."""
        if not isinstance(self.content, str):
            return False
        return bool(self.content.strip())


    def to_dict(self) -> dict[str, Any]:
        return {
            "artifact_id": self.artifact_id,
            "artifact_type": self.artifact_type,
            "content": self.content,
            "location": self.location,
            "mime_type": self.mime_type,
            "creator": self.creator,
            "created_at": self.created_at,
            "citations": self.citations,
            "metadata": self.metadata,
            "session_id": self.session_id,
            "owner": self.owner,
            "tags": self.tags,
            "verification_report": (
                self.verification_report.to_dict() if self.verification_report else None
            ),
        }


@dataclass(frozen=True)
class ResearchArtifact(Artifact):
    query: str = ""
    title: str = ""
    executive_summary: str = ""
    findings: list[dict[str, Any]] = field(default_factory=list)
    references: list[dict[str, Any]] = field(default_factory=list)
    confidence: float = 0.97
    engine: str = "Gemini"

    def __post_init__(self):
        object.__setattr__(self, "artifact_type", "research")
        object.__setattr__(self, "mime_type", "application/json")
        self.metadata.update(
            {
                "query": self.query,
                "title": self.title,
                "summary": self.executive_summary,
                "findings": self.findings,
                "sources": self.references,
                "confidence": self.confidence,
                "engine": self.engine,
            }
        )
        import json

        object.__setattr__(self, "content", json.dumps(self.metadata))


@dataclass(frozen=True)
class CodeArtifact(Artifact):
    language: str = "python"
    code: str = ""
    imports: list[str] = field(default_factory=list)

    def __post_init__(self):
        object.__setattr__(self, "artifact_type", "code")
        object.__setattr__(self, "mime_type", "text/x-python")
        self.metadata.update(
            {
                "language": self.language,
                "code": self.code,
                "imports": self.imports,
            }
        )
        object.__setattr__(self, "content", self.code)


@dataclass(frozen=True)
class DocumentArtifact(Artifact):
    title: str = ""
    body: str = ""
    doc_format: str = "markdown"

    def __post_init__(self):
        object.__setattr__(self, "artifact_type", "document")
        object.__setattr__(self, "mime_type", "text/markdown")
        self.metadata.update(
            {
                "title": self.title,
                "body": self.body,
                "doc_format": self.doc_format,
            }
        )
        object.__setattr__(self, "content", self.body)


@dataclass(frozen=True)
class ImageArtifact(Artifact):
    image_path: str = ""
    dimensions: tuple[int, int] = (1920, 1080)

    def __post_init__(self):
        object.__setattr__(self, "artifact_type", "image")
        object.__setattr__(self, "mime_type", "image/png")
        self.metadata.update(
            {
                "image_path": self.image_path,
                "dimensions": self.dimensions,
            }
        )
        object.__setattr__(self, "content", self.image_path)


@dataclass(frozen=True)
class MemoryArtifact(Artifact):
    key: str = ""
    value: str = ""

    def __post_init__(self):
        object.__setattr__(self, "artifact_type", "memory")
        object.__setattr__(self, "mime_type", "text/plain")
        self.metadata.update(
            {
                "key": self.key,
                "value": self.value,
            }
        )
        object.__setattr__(self, "content", self.value)


@dataclass(frozen=True)
class SessionSummaryArtifact(Artifact):
    date: str = ""
    runtime_id: str = ""
    summary: str = ""
    actions: list[str] = field(default_factory=list)
    timeline_events: list[dict[str, Any]] = field(default_factory=list)
    artifact_count: int = 0
    verification_status: str = "success"

    def __post_init__(self):
        object.__setattr__(self, "artifact_type", "session_summary")
        object.__setattr__(self, "mime_type", "text/markdown")
        self.metadata.update(
            {
                "date": self.date,
                "runtime_id": self.runtime_id,
                "summary": self.summary,
                "actions": self.actions,
                "timeline_events": self.timeline_events,
                "artifact_count": self.artifact_count,
                "verification_status": self.verification_status,
            }
        )
        object.__setattr__(self, "content", self.summary)
