"""
Personal Operating System Integration Runtime (Aura OS Unified Runtime)
Location: src/core/orchestration/personal_os_runtime.py

Unifies Perception, STT/TTS Voice Loop, Proactive Event Runtime, Decision Engine,
Domain Expert Systems, Execution Policy Governance, Execution Coordinator, and Goal Verifier
into a single coherent daily operating system runtime.

INVARIANT: Zero new brains, routers, DMMs, or competing planners introduced.
Rule: Proves that the existing ACA cognitive architecture is sufficient to operate as a Personal AI OS.
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field
from typing import Any
from collections.abc import Callable

from brain.aca.engine_interface import EngineRegistry
from brain.execution_coordinator import ExecutionCoordinator, CoordinationResult
from brain.goal_verifier import GoalVerifier
from experts import DomainExpertRegistry, DomainType
from autonomy.trigger_scheduler import TriggerScheduler
from autonomy.trigger_registry import TriggerRegistry
from brain.executive.dmm import DecisionMakingModule
from brain.executive.execution_map import ExecutionMap
from core.nlu.nlu_engine import NLUEngine
from core.orchestration.activity_trace_renderer import ActivityTraceRenderer
from core.orchestration.execution_policy import ExecutionPolicy, PolicyAction
from core.orchestration.reference_resolver import ReferenceResolver
from core.orchestration.runtime_checkpoint import RuntimeCheckpointManager
from voice.continuous_loop import ContinuousVoiceLoop
from memory.manager.memory_manager import MemoryManager
from ai.provider_manager import ProviderManager

logger = logging.getLogger(__name__)


@dataclass
class RuntimeExecutionReport:
    """Unified execution report generated by PersonalOSRuntime for every goal."""

    goal: str
    input_type: str  # "text", "voice", "event"
    success: bool
    status: str  # "SUCCESS", "RECOVERED_SUCCESS", "BLOCKED", "FAILED"
    worked_time_ms: float
    intent_type: str
    domain_expert_used: str | None = None
    steps_executed: int = 0
    activity_trace_l1: str = ""
    activity_trace_l2: str = ""
    verification_passed: bool = False
    evidence: list[str] = field(default_factory=list)
    spoken_summary: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "goal": self.goal,
            "input_type": self.input_type,
            "success": self.success,
            "status": self.status,
            "worked_time_ms": self.worked_time_ms,
            "intent_type": self.intent_type,
            "domain_expert_used": self.domain_expert_used,
            "steps_executed": self.steps_executed,
            "activity_trace_l1": self.activity_trace_l1,
            "activity_trace_l2": self.activity_trace_l2,
            "verification_passed": self.verification_passed,
            "evidence": self.evidence,
            "spoken_summary": self.spoken_summary,
        }


class PersonalOSRuntime:
    """
    Unified Personal Operating System Runtime orchestrating all Aura sub-runtimes.
    """

    _instance: PersonalOSRuntime | None = None

    def __init__(self):
        self.engine_registry = EngineRegistry.get_instance()
        self.expert_registry = DomainExpertRegistry.get_instance()
        self.trigger_registry = TriggerRegistry()
        self.policy = ExecutionPolicy.get_instance()
        self.coordinator = ExecutionCoordinator()
        self.verifier = GoalVerifier()
        self.nlu_engine = NLUEngine()
        self.dmm = DecisionMakingModule()
        self.reference_resolver = ReferenceResolver()
        self.checkpoint_manager = RuntimeCheckpointManager()
        
        # Central memory coordination
        self.provider_manager = ProviderManager()
        self.memory_manager = MemoryManager(provider_manager=self.provider_manager)
        
        self.trigger_scheduler = TriggerScheduler(
            registry=self.trigger_registry,
            coordinator=self.coordinator,
            policy=self.policy,
        )
        self.voice_loop = ContinuousVoiceLoop(
            coordinator=self.coordinator,
            nlu_engine=self.nlu_engine,
        )

        self._booted = False
        self.turn_history: list[RuntimeExecutionReport] = []
        self._on_report_listeners: list[Callable[[RuntimeExecutionReport], None]] = []

    @classmethod
    def get_instance(cls) -> PersonalOSRuntime:
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    @classmethod
    def reset_instance(cls) -> None:
        if cls._instance is not None:
            if cls._instance.trigger_scheduler._running:
                try:
                    loop = asyncio.get_running_loop()
                    loop.create_task(cls._instance.trigger_scheduler.stop())
                except RuntimeError:
                    asyncio.run(cls._instance.trigger_scheduler.stop())
            if cls._instance.voice_loop._running:
                cls._instance.voice_loop.stop()
                # M2: trigger session-close consolidation (idempotent)
                try:
                    cls._instance.memory_manager.close_session()
                except Exception as _mem_exc:
                    logger.debug(f"[PersonalOSRuntime] close_session skipped: {_mem_exc}")
            cls._instance = None

    def boot(self) -> dict[str, Any]:
        """Boot all Personal OS runtime subsystems cleanly."""
        if self._booted:
            return {"status": "ALREADY_BOOTED", "subsystems_ready": True}

        logger.info("Booting Aura Personal Operating System Runtime...")
        self.voice_loop.start()
        asyncio.create_task(self.trigger_scheduler.start())

        self._booted = True
        return {
            "status": "BOOTED",
            "voice_loop_active": self.voice_loop._running,
            "trigger_scheduler_active": True,
            "registered_engines": list(self.engine_registry._engines.keys()),
            "registered_experts": list(self.expert_registry._experts.keys()),
            "subsystems_ready": True,
        }

    def _resolve_expert_domains(self, query: str) -> list[DomainType]:
        """Determine all expert domains mapped in query."""
        q_lower = query.lower()
        domains = []
        if any(w in q_lower for w in ("ast", "refactor", "module", "codebase", "repository", "class", "function", "software")):
            domains.append(DomainType.SOFTWARE_ENGINEERING)
        if any(w in q_lower for w in ("dns", "tcp", "tls", "ssl", "ping", "port", "network", "reachability")):
            domains.append(DomainType.NETWORK_DIAGNOSTICS)
        if any(w in q_lower for w in ("security", "audit", "permission", "world-writable", "secret", "privilege", "posture")):
            domains.append(DomainType.CYBERSECURITY_AUDIT)
        if any(w in q_lower for w in ("financial", "cagr", "margin", "revenue", "cogs", "growth", "tabular", "csv")):
            domains.append(DomainType.FINANCIAL_ANALYSIS)
        return domains

    def _resolve_expert_domain(self, query: str) -> DomainType | None:
        """Determine if query maps to an expert domain in DomainExpertRegistry."""
        doms = self._resolve_expert_domains(query)
        return doms[0] if doms else None

    def _step_to_action(self, step: Any, goal: str = "") -> tuple[str, str]:
        """Normalize engine and action from DMM ExecutionStep or Expert ExecutionStep."""
        eng = getattr(step, "engine", None)
        if not eng or eng == "none":
            cap = getattr(step, "capability", None)
            eng = cap.value if hasattr(cap, "value") else "desktop"

        desc = str(getattr(step, "description", "")).lower()
        params = getattr(step, "parameters", {})
        param_str = str(params).lower()
        goal_lower = goal.lower()

        if any(w in desc or w in param_str or w in goal_lower for w in ("delete", "remove", "unlink", "drop", "destroy")):
            return "desktop", "file.delete"

        act = getattr(step, "action", None) or params.get("action") or params.get("capability")
        if not act or act == "none":
            st_val = getattr(step, "step_type", "")
            if hasattr(st_val, "value"):
                st_val = st_val.value
            st_val = str(st_val).lower()
            if st_val == "click":
                act = "mouse.click"
            elif st_val == "launch":
                act = "open_app"
            elif st_val == "navigate":
                act = "browser.navigate"
            elif st_val == "write":
                act = "keyboard.type"
            elif st_val == "verify":
                act = "open_app"
            else:
                act = "open_app"

        if eng in ("none", "desktop") and any(k in str(act) for k in ("browser", "navigate", "url", "table", "form")):
            eng = "browser"

        return str(eng), str(act)

    async def execute_goal(
        self,
        goal: str,
        input_type: str = "text",
        context: dict[str, Any] | None = None,
    ) -> RuntimeExecutionReport:
        """
        Single unified entry point for processing text, voice, or proactive event goals.
        Routes through NLU -> Decision -> Context -> Governance -> Coordinator -> Verifier -> Observability.
        """
        start_time = time.perf_counter()
        ctx = context or {}

        # 0. Memory - Log user turn
        self.memory_manager.add_user_turn(goal)

        # 1. NLU & Contextual Follow-Up Resolution (G3)
        mem_ctx = {"memory_context": " ".join([t.content for t in self.memory_manager.get_raw_turns()])}
        resolved_goal = self.reference_resolver.resolve_references(goal, {**ctx, **mem_ctx})[0]
        nlu_res = self.nlu_engine.process(resolved_goal, ctx)
        
        normalized_goal = nlu_res.normalized_text

        # 2. Decision Engine (DMM) & Expert System Routing (G5)
        expert_domains = self._resolve_expert_domains(normalized_goal)

        exec_map = None
        expert_used_name = None

        if expert_domains:
            combined_steps = []
            combined_summaries = []
            used_names = []
            for domain in expert_domains:
                expert = self.expert_registry.resolve(domain)
                if expert:
                    expert_analysis = expert.analyze(normalized_goal, ctx)
                    used_names.append(domain.value)
                    combined_summaries.append(f"[{domain.value.upper()}]: {expert_analysis.summary}")
                    for prop in expert_analysis.proposals:
                        combined_steps.append({
                            "engine": prop.engine,
                            "action": prop.action,
                            "parameters": prop.parameters,
                        })
            if used_names:
                expert_used_name = ", ".join(used_names)
                if not combined_steps:
                    combined_steps = [
                        {
                            "engine": "desktop",
                            "action": "chat",
                            "parameters": {"response": " | ".join(combined_summaries)},
                        }
                    ]
                exec_map = {"goal": normalized_goal, "steps": combined_steps}

        if exec_map is None:
            dmm_res = self.dmm.analyze(normalized_goal, ctx)
            if isinstance(dmm_res, ExecutionMap):
                exec_map = dmm_res
            else:
                exec_map = ExecutionMap(goal=normalized_goal, execution_plan=[])

        # 3. Policy & Governance Enforcer (G7)
        if isinstance(exec_map, dict):
            steps_list = exec_map.get("steps", exec_map.get("execution_plan", []))
        else:
            steps_list = getattr(exec_map, "steps", getattr(exec_map, "execution_plan", []))
        formatted_steps: list[dict[str, Any]] = []

        for step in steps_list:
            eng, act = self._step_to_action(step, goal=resolved_goal)
            params = getattr(step, "parameters", {})
            formatted_steps.append({"engine": eng, "action": act, "parameters": params})

            pol_dec = self.policy.evaluate_action(eng, act, params)
            if pol_dec.action == PolicyAction.FAIL or (pol_dec.action == PolicyAction.ASK_USER and not ctx.get("user_authorized", False)):
                elapsed_ms = (time.perf_counter() - start_time) * 1000.0
                step_id_val = getattr(step, "step_id", "step_0")
                report = RuntimeExecutionReport(
                    goal=goal,
                    input_type=input_type,
                    success=False,
                    status="BLOCKED",
                    worked_time_ms=elapsed_ms,
                    intent_type=expert_used_name or getattr(nlu_res, "intent_hint", "general"),
                    domain_expert_used=expert_used_name,
                    steps_executed=0,
                    activity_trace_l1=f"[POLICY BLOCKED] {pol_dec.message}",
                    activity_trace_l2=f"[POLICY REJECT] Step {step_id_val} ({eng}.{act}): {pol_dec.message}",
                    verification_passed=False,
                    evidence=[f"Policy Status: {pol_dec.action.name}", f"Reason: {pol_dec.message}"],
                    spoken_summary=f"Operation blocked by security policy: {pol_dec.message}",
                )
                self.turn_history.append(report)
                return report

        # 4. Execution Coordinator Loop (Execute -> Observe -> Verify -> Recover) (G4, G8, G9)
        map_dict = {
            "goal": getattr(exec_map, "goal", goal),
            "steps": formatted_steps,
        }
        coord_res: CoordinationResult = await self.coordinator.coordinate(map_dict)

        elapsed_ms = (time.perf_counter() - start_time) * 1000.0

        # Update Runtime Checkpoint & Trace Observability (G10, G11)
        # self.checkpoint_manager handles session state persistence
        steps_cnt = len(coord_res.step_results)

        l1_trace = ActivityTraceRenderer.render_compact(coord_res)
        l2_trace = ActivityTraceRenderer.render_summary(coord_res)

        verification_passed = False
        evidence_list: list[str] = []
        if "goal_verification" in coord_res.data:
            verification_passed = coord_res.data["goal_verification"].get("passed", False)
            evidence_list = coord_res.data["goal_verification"].get("evidence", [])

        spoken = f"Goal '{goal}' completed successfully." if coord_res.success else f"Goal '{goal}' failed execution."

        status_str = "SUCCESS"
        if coord_res.success and len(coord_res.failed_steps) > 0:
            status_str = "RECOVERED_SUCCESS"
        elif not coord_res.success:
            status_str = "FAILED"

        report = RuntimeExecutionReport(
            goal=goal,
            input_type=input_type,
            success=coord_res.success,
            status=status_str,
            worked_time_ms=elapsed_ms,
            intent_type=expert_used_name or getattr(nlu_res, "intent_hint", "general"),
            domain_expert_used=expert_used_name,
            steps_executed=steps_cnt,
            activity_trace_l1=l1_trace,
            activity_trace_l2=l2_trace,
            verification_passed=verification_passed,
            evidence=evidence_list,
            spoken_summary=spoken,
        )

        # Log assistant turn to memory (if there's a spoken summary)
        if report.spoken_summary:
            self.memory_manager.add_assistant_turn(report.spoken_summary, user_text=resolved_goal)

        self.turn_history.append(report)
        for listener in self._on_report_listeners:
            try:
                listener(report)
            except Exception as e:
                logger.warning(f"Error in report listener: {e}")

        return report
