"""
Domain Expert Models & Data Contracts
Location: src/experts/models.py

Defines standard data structures for domain analysis findings, proposals, and result packages.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class DomainType(Enum):
    """Supported Professional Expert System domains."""

    SOFTWARE_ENGINEERING = "software_engineering"
    NETWORK_DIAGNOSTICS = "network_diagnostics"
    CYBERSECURITY_AUDIT = "cybersecurity_audit"
    FINANCIAL_ANALYSIS = "financial_analysis"
    UNSUPPORTED = "unsupported"


class SeverityLevel(Enum):
    """Finding severity classification."""

    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class DomainFinding:
    """A single finding or observation produced by a domain expert."""

    category: str
    title: str
    description: str
    severity: SeverityLevel = SeverityLevel.INFO
    evidence: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "category": self.category,
            "title": self.title,
            "description": self.description,
            "severity": self.severity.value,
            "evidence": self.evidence,
        }


@dataclass
class DomainActionProposal:
    """A proposed step/action generated by a domain expert (NEVER directly executed by expert)."""

    engine: str
    action: str
    parameters: dict[str, Any] = field(default_factory=dict)
    description: str = ""
    risk_level: str = "low"

    def to_dict(self) -> dict[str, Any]:
        return {
            "engine": self.engine,
            "action": self.action,
            "parameters": self.parameters,
            "description": self.description,
            "risk_level": self.risk_level,
        }


@dataclass
class ExpertAnalysisResult:
    """Deterministic result package returned by all Domain Expert Systems."""

    domain: DomainType
    success: bool
    summary: str
    findings: list[DomainFinding] = field(default_factory=list)
    proposals: list[DomainActionProposal] = field(default_factory=list)
    error: str = ""
    data: dict[str, Any] = field(default_factory=dict)

    def to_execution_map(self, goal: str) -> dict[str, Any]:
        """Convert proposed actions into an execution map for ExecutionCoordinator."""
        steps = []
        for prop in self.proposals:
            steps.append({
                "engine": prop.engine,
                "action": prop.action,
                "parameters": prop.parameters,
            })
        return {
            "goal": f"[Domain: {self.domain.value}] {goal}",
            "steps": steps,
            "domain_context": {
                "summary": self.summary,
                "findings_count": len(self.findings),
            },
        }

    def to_dict(self) -> dict[str, Any]:
        return {
            "domain": self.domain.value,
            "success": self.success,
            "summary": self.summary,
            "findings": [f.to_dict() for f in self.findings],
            "proposals": [p.to_dict() for p in self.proposals],
            "error": self.error,
            "data": self.data,
        }
