"""
Design Token Exporter & Drift Engine
====================================
Location: src/engineering/token_exporter.py

Single source of truth extraction: Reads design tokens from src/gui/theme.py
and deterministically generates tokens.json, tailwind.config.js, and aura-theme.css.
Includes automated drift checking with SHA-256 token hashing for SSIM baseline governance.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import sys
from pathlib import Path
from typing import Any, Dict, Tuple

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
_SRC_DIR = _PROJECT_ROOT / "src"
if str(_SRC_DIR) not in sys.path:
    sys.path.insert(0, str(_SRC_DIR))
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(1, str(_PROJECT_ROOT))

from gui.theme import Colors, Radius, Spacing, Typography

logger = logging.getLogger(__name__)

TEMPLATES_DIR = _SRC_DIR / "engineering" / "templates"


def _clean_token_name(name: str) -> str:
    """Converts UPPER_CASE to kebab-case (e.g. BG_DEEP -> bg-deep)."""
    return name.lower().replace("_", "-")


def extract_canonical_tokens() -> Dict[str, Any]:
    """
    Extracts all canonical tokens from theme.py classes into a clean structured dictionary.
    """
    # 1. Colors
    colors = {}
    for attr in dir(Colors):
        if attr.isupper():
            val = getattr(Colors, attr)
            if isinstance(val, str) and not val.startswith("qlineargradient"):
                colors[_clean_token_name(attr)] = val

    # 2. Typography
    typography = {
        "family": Typography.FAMILY,
        "mono": "Consolas, Fira Code, monospace",
    }

    # 3. Spacing
    spacing = {}
    for attr in dir(Spacing):
        if attr.isupper():
            val = getattr(Spacing, attr)
            if isinstance(val, int):
                spacing[_clean_token_name(attr)] = f"{val}px"

    # 4. Radius
    radius = {}
    for attr in dir(Radius):
        if attr.isupper():
            val = getattr(Radius, attr)
            if isinstance(val, str):
                radius[_clean_token_name(attr)] = val

    token_data = {
        "version": "1.0.0",
        "colors": colors,
        "typography": typography,
        "spacing": spacing,
        "radius": radius,
    }

    # Compute deterministic SHA-256 hash
    canonical_json = json.dumps(token_data, sort_keys=True, indent=2)
    token_hash = hashlib.sha256(canonical_json.encode("utf-8")).hexdigest()[:16]
    token_data["token_hash"] = token_hash

    return token_data


def generate_tokens_json(tokens: Dict[str, Any]) -> str:
    """Generates formatted JSON string with metadata."""
    return json.dumps(tokens, indent=2, sort_keys=True) + "\n"


def generate_tailwind_config(tokens: Dict[str, Any]) -> str:
    """Generates tailwind.config.js referencing the canonical tokens."""
    colors = tokens["colors"]
    radius = tokens["radius"]
    token_hash = tokens.get("token_hash", "")

    color_entries = []
    for k, v in sorted(colors.items()):
        color_entries.append(f"        '{k}': '{v}',")
    colors_block = "\n".join(color_entries)

    radius_entries = []
    for k, v in sorted(radius.items()):
        radius_entries.append(f"        'aura-{k}': '{v}',")
    radius_block = "\n".join(radius_entries)

    return f"""/**
 * AuraAI Design-Token Tailwind Theme Extension
 * Auto-generated by src/engineering/token_exporter.py
 * Token Hash: {token_hash}
 * DO NOT EDIT DIRECTLY. Update src/gui/theme.py and run token_exporter.py.
 */

/** @type {{import('tailwindcss').Config}} */
module.exports = {{
  content: [
    "./**/*.{{html,js,jsx,ts,tsx}}",
    "./components/**/*.{{html,jsx,tsx}}"
  ],
  darkMode: "class",
  theme: {{
    extend: {{
      colors: {{
        aura: {{
{colors_block}
        }}
      }},
      fontFamily: {{
        'aura-sans': ['Inter', 'Segoe UI', '-apple-system', 'sans-serif'],
        'aura-mono': ['Consolas', 'Fira Code', 'monospace']
      }},
      borderRadius: {{
{radius_block}
      }},
      boxShadow: {{
        'aura-cyan': '0 0 15px rgba(0, 229, 255, 0.35)',
        'aura-blue': '0 0 15px rgba(80, 170, 255, 0.35)',
        'aura-card': '0 8px 32px rgba(0, 0, 0, 0.45)'
      }}
    }}
  }},
  plugins: []
}};
"""


def generate_aura_theme_css(tokens: Dict[str, Any]) -> str:
    """Generates aura-theme.css with CSS custom variables."""
    colors = tokens["colors"]
    radius = tokens["radius"]
    spacing = tokens["spacing"]
    token_hash = tokens.get("token_hash", "")

    css_vars = []
    css_vars.append("  /* Colors */")
    for k, v in sorted(colors.items()):
        css_vars.append(f"  --aura-{k}: {v};")

    css_vars.append("\n  /* Radius */")
    for k, v in sorted(radius.items()):
        css_vars.append(f"  --aura-radius-{k}: {v};")

    css_vars.append("\n  /* Spacing */")
    for k, v in sorted(spacing.items()):
        css_vars.append(f"  --aura-spacing-{k}: {v};")

    css_vars.append("\n  /* Typography */")
    css_vars.append(f"  --aura-font-sans: {tokens['typography']['family']};")
    css_vars.append(f"  --aura-font-mono: {tokens['typography']['mono']};")

    vars_block = "\n".join(css_vars)

    return f"""/**
 * AuraAI Cyber-HUD Global Theme Variables
 * Auto-generated by src/engineering/token_exporter.py
 * Token Hash: {token_hash}
 */

:root {{
{vars_block}
}}

/* Utility classes for dark cyber glassmorphism */
.aura-glass {{
  background: var(--aura-bg-card);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  border: 1px solid var(--aura-border-subtle);
}}

.aura-glass:hover {{
  border-color: var(--aura-border-active);
}}

.aura-glow-cyan {{
  box-shadow: 0 0 15px rgba(0, 229, 255, 0.35);
}}
"""


def export_tokens(target_dir: Path | None = None) -> Dict[str, Path]:
    """
    Exports tokens.json, tailwind.config.js, and aura-theme.css to the target directory.
    """
    dest = target_dir or TEMPLATES_DIR
    dest.mkdir(parents=True, exist_ok=True)

    tokens = extract_canonical_tokens()

    json_path = dest / "tokens.json"
    tailwind_path = dest / "tailwind.config.js"
    css_path = dest / "aura-theme.css"

    json_path.write_text(generate_tokens_json(tokens), encoding="utf-8")
    tailwind_path.write_text(generate_tailwind_config(tokens), encoding="utf-8")
    css_path.write_text(generate_aura_theme_css(tokens), encoding="utf-8")

    logger.info(f"[TokenExporter] Exported tokens (hash: {tokens['token_hash']}) to {dest}")
    return {
        "tokens_json": json_path,
        "tailwind_config": tailwind_path,
        "aura_css": css_path,
    }


def check_drift(target_dir: Path | None = None) -> Tuple[bool, list[str]]:
    """
    Compares on-disk token files against in-memory canonical theme.py definitions.
    Returns (is_synced, list_of_drift_errors).
    """
    dest = target_dir or TEMPLATES_DIR
    tokens = extract_canonical_tokens()
    expected_hash = tokens["token_hash"]

    errors = []

    json_path = dest / "tokens.json"
    tailwind_path = dest / "tailwind.config.js"
    css_path = dest / "aura-theme.css"

    for p in (json_path, tailwind_path, css_path):
        if not p.exists():
            errors.append(f"Missing token artifact: {p.name}")

    if errors:
        return False, errors

    # Check tokens.json
    try:
        disk_tokens = json.loads(json_path.read_text(encoding="utf-8"))
        if disk_tokens.get("token_hash") != expected_hash:
            errors.append(
                f"tokens.json hash mismatch (disk: {disk_tokens.get('token_hash')}, expected: {expected_hash})"
            )
    except Exception as e:
        errors.append(f"Error parsing tokens.json: {e}")

    # Check tailwind.config.js content match
    expected_tailwind = generate_tailwind_config(tokens).strip()
    if tailwind_path.read_text(encoding="utf-8").strip() != expected_tailwind:
        errors.append("tailwind.config.js content drifted from theme.py")

    # Check aura-theme.css content match
    expected_css = generate_aura_theme_css(tokens).strip()
    if css_path.read_text(encoding="utf-8").strip() != expected_css:
        errors.append("aura-theme.css content drifted from theme.py")

    is_synced = len(errors) == 0
    return is_synced, errors


def main():
    parser = argparse.ArgumentParser(description="AuraAI Design Token Exporter & Drift Checker")
    parser.add_argument("--export", action="store_true", help="Export all token artifacts from theme.py")
    parser.add_argument("--check", action="store_true", help="Verify that on-disk token artifacts match theme.py")
    parser.add_argument("--output-dir", type=Path, default=TEMPLATES_DIR, help="Target directory")

    args = parser.parse_args()

    if args.check:
        synced, errors = check_drift(args.output_dir)
        if synced:
            print(f"[SUCCESS] Token artifacts at {args.output_dir} match theme.py (100% in sync).")
            sys.exit(0)
        else:
            print(f"[DRIFT DETECTED] {len(errors)} token drift issue(s):")
            for err in errors:
                print(f"  • {err}")
            sys.exit(1)
    else:
        # Default action is export
        paths = export_tokens(args.output_dir)
        print(f"[SUCCESS] Exported token files:")
        for k, p in paths.items():
            print(f"  • {k}: {p}")


if __name__ == "__main__":
    main()
