"""
Browser Capability Provider
===========================
Location: src/core/capabilities/providers/browser_provider.py

Provides capability descriptors for the Browser automation subsystem (Playwright).
Marked as scaffolded contracts (is_live=False) until M22 operational wiring is complete.
"""

from __future__ import annotations

from core.capabilities.models import Capability
from core.capabilities.provider import ICapabilityProvider
from core.orchestration.autonomy_mode import ActionRisk


class BrowserCapabilityProvider(ICapabilityProvider):
    """Provider for browser automation and web interaction capabilities."""

    DOMAIN = "browser"

    def __init__(self) -> None:
        self._capabilities: dict[str, Capability] = self._build_capabilities()

    @property
    def domain(self) -> str:
        return self.DOMAIN

    def _build_capabilities(self) -> dict[str, Capability]:
        caps = [
            Capability(
                name="browser",
                domain=self.DOMAIN,
                description="General browser automation and web navigation capability.",
                category="session",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"success": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:session"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=[],
                verifies=[],
                tags=["browser", "session", "live"],
            ),
            Capability(
                name="browser.open",
                domain=self.DOMAIN,
                description="Launch or connect to a Playwright browser session.",
                category="session",
                input_schema={
                    "type": "object",
                    "properties": {"headless": {"type": "boolean", "default": True}},
                },
                output_schema={
                    "type": "object",
                    "properties": {"session_id": {"type": "string"}},
                },
                risk_level=ActionRisk.LOW,
                permissions=["browser:session"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=[],
                verifies=["browser.observe"],
                tags=["browser", "session", "live"],
            ),
            Capability(
                name="browser.navigate",
                domain=self.DOMAIN,
                description="Navigate current browser page to a target URL.",
                category="navigation",
                input_schema={
                    "type": "object",
                    "required": ["url"],
                    "properties": {"url": {"type": "string"}},
                },
                output_schema={
                    "type": "object",
                    "properties": {
                        "status_code": {"type": "integer"},
                        "url": {"type": "string"},
                    },
                },
                risk_level=ActionRisk.LOW,
                permissions=["network:http"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["browser", "navigation", "live"],
            ),
            Capability(
                name="browser.find_element",
                domain=self.DOMAIN,
                description="Find and resolve a unique DOM element matching a CSS or text selector.",
                category="inspection",
                input_schema={
                    "type": "object",
                    "required": ["selector"],
                    "properties": {"selector": {"type": "string"}},
                },
                output_schema={
                    "type": "object",
                    "properties": {
                        "count": {"type": "integer"},
                        "element": {"type": "object"},
                    },
                },
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.navigate"],
                verifies=[],
                tags=["browser", "find", "live"],
            ),
            Capability(
                name="browser.click",
                domain=self.DOMAIN,
                description="Click a DOM element identified by CSS selector or XPath, requiring confirmation for destructive actions.",
                category="interaction",
                input_schema={
                    "type": "object",
                    "required": ["selector"],
                    "properties": {"selector": {"type": "string"}},
                },
                output_schema={
                    "type": "object",
                    "properties": {"clicked": {"type": "boolean"}},
                },
                risk_level=ActionRisk.HIGH,
                is_destructive=True,
                requires_confirmation=True,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.navigate"],
                verifies=["browser.observe"],
                tags=["browser", "click", "mutation", "live"],
            ),
            Capability(
                name="browser.type",
                domain=self.DOMAIN,
                description="Fill or type text into a web input field, requiring confirmation for destructive input.",
                category="interaction",
                input_schema={
                    "type": "object",
                    "required": ["selector", "text"],
                    "properties": {
                        "selector": {"type": "string"},
                        "text": {"type": "string"},
                        "clear": {"type": "boolean", "default": True},
                    },
                },
                output_schema={
                    "type": "object",
                    "properties": {"success": {"type": "boolean"}},
                },
                risk_level=ActionRisk.HIGH,
                is_destructive=True,
                requires_confirmation=True,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.navigate"],
                verifies=["browser.observe"],
                tags=["browser", "type", "mutation", "live"],
            ),
            Capability(
                name="browser.submit",
                domain=self.DOMAIN,
                description="Submit a web form or press Enter on targeted element, requiring confirmation.",
                category="interaction",
                input_schema={
                    "type": "object",
                    "properties": {"selector": {"type": "string"}},
                },
                output_schema={
                    "type": "object",
                    "properties": {"submitted": {"type": "boolean"}},
                },
                risk_level=ActionRisk.HIGH,
                is_destructive=True,
                requires_confirmation=True,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.navigate"],
                verifies=["browser.observe"],
                tags=["browser", "submit", "mutation", "live"],
            ),
            Capability(
                name="browser.extract",
                domain=self.DOMAIN,
                description="Extract structured text, markdown, or table data from the active page.",
                category="extraction",
                input_schema={
                    "type": "object",
                    "properties": {
                        "selector": {"type": "string"},
                        "format": {"type": "string", "default": "markdown"},
                    },
                },
                output_schema={
                    "type": "object",
                    "properties": {"content": {"type": "string"}},
                },
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.navigate"],
                verifies=[],
                tags=["browser", "extract", "live"],
            ),
            Capability(
                name="browser.observe",
                domain=self.DOMAIN,
                description="Capture current page DOM accessibility tree, snapshot, or title.",
                category="observation",
                input_schema={"type": "object", "properties": {}},
                output_schema={
                    "type": "object",
                    "properties": {
                        "title": {"type": "string"},
                        "url": {"type": "string"},
                    },
                },
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["browser", "observe", "live"],
            ),
            Capability(
                name="browser.close",
                domain=self.DOMAIN,
                description="Close active browser session and cleanup page instances.",
                category="session",
                input_schema={"type": "object", "properties": {}},
                output_schema={
                    "type": "object",
                    "properties": {"closed": {"type": "boolean"}},
                },
                risk_level=ActionRisk.LOW,
                permissions=["browser:session"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=[],
                verifies=[],
                tags=["browser", "close", "live"],
            ),
            Capability(
                name="browser.check_auth",
                domain=self.DOMAIN,
                description="Check authentication or login state for a target website.",
                category="auth",
                input_schema={"type": "object", "properties": {"site": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"authenticated": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=[],
                verifies=[],
                tags=["browser", "auth", "live"],
            ),
            Capability(
                name="browser.navigate_goal",
                domain=self.DOMAIN,
                description="Navigate to a high-level goal URL or site section.",
                category="navigation",
                input_schema={"type": "object", "properties": {"url": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"success": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["network:http"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["browser", "navigation", "live"],
            ),
            Capability(
                name="browser.search",
                domain=self.DOMAIN,
                description="Perform a search query on a target website.",
                category="navigation",
                input_schema={"type": "object", "properties": {"query": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"results": {"type": "array"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["browser", "search", "live"],
            ),
            Capability(
                name="browser.select_video",
                domain=self.DOMAIN,
                description="Select and play a specific video result on YouTube or media site.",
                category="media",
                input_schema={"type": "object", "properties": {"query": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"selected": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["browser", "media", "live"],
            ),
            Capability(
                name="browser.verify_video",
                domain=self.DOMAIN,
                description="Verify video playback is active.",
                category="media",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"playing": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["browser", "media", "live"],
            ),
            Capability(
                name="browser.scroll",
                domain=self.DOMAIN,
                description="Scroll active browser page.",
                category="navigation",
                input_schema={"type": "object", "properties": {"direction": {"type": "string", "default": "down"}}},
                output_schema={"type": "object", "properties": {"scrolled": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["browser", "scroll", "live"],
            ),
            Capability(
                name="shopping.search",
                domain=self.DOMAIN,
                description="Search for products on an e-commerce platform.",
                category="shopping",
                input_schema={"type": "object", "properties": {"query": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"items": {"type": "array"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["shopping", "search", "live"],
            ),
            Capability(
                name="shopping.cart",
                domain=self.DOMAIN,
                description="View or manage items in shopping cart.",
                category="shopping",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"cart_items": {"type": "array"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["shopping", "cart", "live"],
            ),
            Capability(
                name="shopping.checkout",
                domain=self.DOMAIN,
                description="Initiate checkout process on e-commerce platform.",
                category="shopping",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"checkout_started": {"type": "boolean"}}},
                risk_level=ActionRisk.CRITICAL,
                is_destructive=True,
                requires_confirmation=True,
                permissions=["shopping:purchase"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["shopping", "checkout", "mutation", "live"],
            ),
            Capability(
                name="browser.ensure_open",
                domain=self.DOMAIN,
                description="Ensure an active browser session is open and ready.",
                category="session",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"ready": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:session"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=[],
                verifies=[],
                tags=["browser", "session", "live"],
            ),
            Capability(
                name="browser.close_tabs",
                domain=self.DOMAIN,
                description="Close inactive or excessive browser tabs.",
                category="session",
                input_schema={"type": "object", "properties": {"keep_active": {"type": "boolean", "default": True}}},
                output_schema={"type": "object", "properties": {"closed_count": {"type": "integer"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:session"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["browser", "tabs", "live"],
            ),
            Capability(
                name="browser.list_tabs",
                domain=self.DOMAIN,
                description="List all currently open browser tabs.",
                category="inspection",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"tabs": {"type": "array"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["browser", "tabs", "live"],
            ),
            Capability(
                name="browser.switch_tab",
                domain=self.DOMAIN,
                description="Switch active view to a target browser tab index or title.",
                category="navigation",
                input_schema={"type": "object", "properties": {"index": {"type": "integer"}, "title": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"active_tab": {"type": "string"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["browser", "tabs", "live"],
            ),
            Capability(
                name="browser.next_page",
                domain=self.DOMAIN,
                description="Navigate to next page in search results or pagination.",
                category="navigation",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"success": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["browser", "pagination", "live"],
            ),
            Capability(
                name="browser.pagination",
                domain=self.DOMAIN,
                description="Navigate through paginated result pages.",
                category="navigation",
                input_schema={"type": "object", "properties": {"page_number": {"type": "integer"}}},
                output_schema={"type": "object", "properties": {"page": {"type": "integer"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["browser", "pagination", "live"],
            ),
            Capability(
                name="browser.comments",
                domain=self.DOMAIN,
                description="Inspect or extract user comments from active media or post.",
                category="extraction",
                input_schema={"type": "object", "properties": {"limit": {"type": "integer", "default": 10}}},
                output_schema={"type": "object", "properties": {"comments": {"type": "array"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["browser", "comments", "live"],
            ),
            Capability(
                name="browser.reviews",
                domain=self.DOMAIN,
                description="Extract user reviews and ratings from active page.",
                category="extraction",
                input_schema={"type": "object", "properties": {"limit": {"type": "integer", "default": 10}}},
                output_schema={"type": "object", "properties": {"reviews": {"type": "array"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["browser", "reviews", "live"],
            ),
            Capability(
                name="social.search",
                domain=self.DOMAIN,
                description="Search social media platforms for queries or hashtags.",
                category="social",
                input_schema={"type": "object", "properties": {"query": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"results": {"type": "array"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["social", "search", "live"],
            ),
            Capability(
                name="social.inspect_result",
                domain=self.DOMAIN,
                description="Inspect specific social media post or profile.",
                category="social",
                input_schema={"type": "object", "properties": {"index": {"type": "integer"}}},
                output_schema={"type": "object", "properties": {"content": {"type": "string"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["social", "inspect", "live"],
            ),
            Capability(
                name="social.verify_result",
                domain=self.DOMAIN,
                description="Verify post or profile authenticity and visibility.",
                category="social",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"verified": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["social", "verify", "live"],
            ),
            Capability(
                name="form.inspect",
                domain=self.DOMAIN,
                description="Inspect and identify input fields in an active web form.",
                category="form",
                input_schema={"type": "object", "properties": {"selector": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"fields": {"type": "array"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["form", "inspect", "live"],
            ),
            Capability(
                name="form.fill",
                domain=self.DOMAIN,
                description="Populate multiple form fields with structured data.",
                category="form",
                input_schema={"type": "object", "properties": {"fields": {"type": "object"}}},
                output_schema={"type": "object", "properties": {"filled": {"type": "boolean"}}},
                risk_level=ActionRisk.HIGH,
                is_destructive=True,
                requires_confirmation=True,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["form", "fill", "mutation", "live"],
            ),
            Capability(
                name="form.submit",
                domain=self.DOMAIN,
                description="Submit the active web form.",
                category="form",
                input_schema={"type": "object", "properties": {"selector": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"submitted": {"type": "boolean"}}},
                risk_level=ActionRisk.HIGH,
                is_destructive=True,
                requires_confirmation=True,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["form", "submit", "mutation", "live"],
            ),
            Capability(
                name="table.extract",
                domain=self.DOMAIN,
                description="Extract structured tabular data from an HTML table.",
                category="extraction",
                input_schema={"type": "object", "properties": {"selector": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"rows": {"type": "array"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["table", "extract", "live"],
            ),
            Capability(
                name="table.select_row",
                domain=self.DOMAIN,
                description="Select or click a specific row in a data table.",
                category="interaction",
                input_schema={"type": "object", "properties": {"row_index": {"type": "integer"}}},
                output_schema={"type": "object", "properties": {"selected": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["table", "interaction", "live"],
            ),
            Capability(
                name="shopping.filter",
                domain=self.DOMAIN,
                description="Apply filters (price, rating, brand) to shopping results.",
                category="shopping",
                input_schema={"type": "object", "properties": {"filters": {"type": "object"}}},
                output_schema={"type": "object", "properties": {"applied": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["browser.observe"],
                tags=["shopping", "filter", "live"],
            ),
            Capability(
                name="shopping.compare",
                domain=self.DOMAIN,
                description="Compare specifications and pricing across shopping items.",
                category="shopping",
                input_schema={"type": "object", "properties": {"item_ids": {"type": "array"}}},
                output_schema={"type": "object", "properties": {"comparison": {"type": "object"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["shopping", "compare", "live"],
            ),
            Capability(
                name="shopping.reviews",
                domain=self.DOMAIN,
                description="Extract verified product reviews and sentiment.",
                category="shopping",
                input_schema={"type": "object", "properties": {"item_id": {"type": "string"}}},
                output_schema={"type": "object", "properties": {"reviews": {"type": "array"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:read"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["shopping", "reviews", "live"],
            ),
            Capability(
                name="shopping.cart.add",
                domain=self.DOMAIN,
                description="Add an item to the shopping cart.",
                category="shopping",
                input_schema={"type": "object", "properties": {"item_id": {"type": "string"}, "quantity": {"type": "integer", "default": 1}}},
                output_schema={"type": "object", "properties": {"added": {"type": "boolean"}}},
                risk_level=ActionRisk.MEDIUM,
                is_destructive=False,
                requires_confirmation=False,
                permissions=["shopping:cart"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=["shopping.cart"],
                tags=["shopping", "cart", "mutation", "live"],
            ),
            Capability(
                name="media.play",
                domain=self.DOMAIN,
                description="Play active web video or audio media.",
                category="media",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"playing": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["media", "playback", "live"],
            ),
            Capability(
                name="media.pause",
                domain=self.DOMAIN,
                description="Pause active web video or audio media.",
                category="media",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"paused": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["media", "playback", "live"],
            ),
            Capability(
                name="media.resume",
                domain=self.DOMAIN,
                description="Resume paused web video or audio media.",
                category="media",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"resumed": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["media", "playback", "live"],
            ),
            Capability(
                name="media.stop",
                domain=self.DOMAIN,
                description="Stop active web video or audio media.",
                category="media",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"stopped": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["media", "playback", "live"],
            ),
            Capability(
                name="media.next",
                domain=self.DOMAIN,
                description="Skip to next track or video.",
                category="media",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"skipped": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["media", "playback", "live"],
            ),
            Capability(
                name="media.previous",
                domain=self.DOMAIN,
                description="Return to previous track or video.",
                category="media",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"previous": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["media", "playback", "live"],
            ),
            Capability(
                name="media.restart",
                domain=self.DOMAIN,
                description="Restart media playback from beginning.",
                category="media",
                input_schema={"type": "object", "properties": {}},
                output_schema={"type": "object", "properties": {"restarted": {"type": "boolean"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["media", "playback", "live"],
            ),
            Capability(
                name="media.seek",
                domain=self.DOMAIN,
                description="Seek to specific time offset in media playback.",
                category="media",
                input_schema={"type": "object", "properties": {"offset_seconds": {"type": "number"}}},
                output_schema={"type": "object", "properties": {"position": {"type": "number"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["media", "playback", "live"],
            ),
            Capability(
                name="media.volume",
                domain=self.DOMAIN,
                description="Adjust media player volume percentage.",
                category="media",
                input_schema={"type": "object", "properties": {"volume": {"type": "number", "minimum": 0.0, "maximum": 1.0}}},
                output_schema={"type": "object", "properties": {"volume": {"type": "number"}}},
                risk_level=ActionRisk.LOW,
                permissions=["browser:interact"],
                execution_backend="browser",
                is_live=True,
                availability="available",
                requires=["browser.open"],
                verifies=[],
                tags=["media", "volume", "live"],
            ),
        ]
        return {cap.name: cap for cap in caps}

    def list_capabilities(self) -> list[Capability]:
        return list(self._capabilities.values())

    def get_capability(self, name: str) -> Capability | None:
        return self._capabilities.get(name)
