/**
 * AuraAI Design-Token Tailwind Theme Extension
 * Auto-generated by src/engineering/token_exporter.py
 * Token Hash: 1c620776dfc55408
 * DO NOT EDIT DIRECTLY. Update src/gui/theme.py and run token_exporter.py.
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./**/*.{html,js,jsx,ts,tsx}",
    "./components/**/*.{html,jsx,tsx}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        aura: {
        'amber': '#fbbf24',
        'bg-card': 'rgba(22, 28, 40, 0.85)',
        'bg-card-hover': 'rgba(32, 42, 60, 0.95)',
        'bg-deep': '#0d1117',
        'bg-input': 'rgba(18, 23, 34, 0.9)',
        'bg-overlay': 'rgba(16, 20, 28, 0.92)',
        'bg-sidebar': '#0c1017',
        'bg-slate': '#121722',
        'bg-surface': '#161c28',
        'bg-toolbar': '#0e131d',
        'blue': '#50aaff',
        'blue-glow': '#80c4ff',
        'border-accent': 'rgba(0, 229, 255, 0.85)',
        'border-active': 'rgba(0, 229, 255, 0.4)',
        'border-subtle': 'rgba(255, 255, 255, 0.08)',
        'crimson': '#f43f5e',
        'cyan': '#00e5ff',
        'cyan-dim': 'rgba(0, 229, 255, 0.15)',
        'cyan-glow': '#33eeff',
        'emerald': '#10b981',
        'error': '#f43f5e',
        'info': '#50aaff',
        'overlay-bg': 'rgba(16, 20, 28, 0.92)',
        'overlay-border': 'rgba(0, 229, 255, 0.45)',
        'purple': '#818cf8',
        'purple-glow': '#a5b4fc',
        'success': '#10b981',
        'text-disabled': '#3e4c60',
        'text-muted': '#627289',
        'text-primary': '#f3f6fc',
        'text-secondary': '#a5b4cb',
        'warning': '#fbbf24',
        }
      },
      fontFamily: {
        'aura-sans': ['Inter', 'Segoe UI', '-apple-system', 'sans-serif'],
        'aura-mono': ['Consolas', 'Fira Code', 'monospace']
      },
      borderRadius: {
        'aura-lg': '14px',
        'aura-md': '10px',
        'aura-pill': '9999px',
        'aura-sm': '6px',
        'aura-xl': '20px',
      },
      boxShadow: {
        'aura-cyan': '0 0 15px rgba(0, 229, 255, 0.35)',
        'aura-blue': '0 0 15px rgba(80, 170, 255, 0.35)',
        'aura-card': '0 8px 32px rgba(0, 0, 0, 0.45)'
      }
    }
  },
  plugins: []
};
