"""
Desktop Plan Representation
Constructed execution graph containing steps, dependencies, and execution state.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from .desktop_goal import DesktopGoal
from .desktop_step import DesktopStep, StepStatus
from .planner_state import PlanState, PlanStateTracker


@dataclass
class DesktopPlan:
    """
    Execution plan generated by DesktopPlanner.
    """

    plan_id: str
    goal: DesktopGoal
    steps: list[DesktopStep] = field(default_factory=list)
    state_tracker: PlanStateTracker = field(default_factory=PlanStateTracker)
    created_at: datetime = field(default_factory=datetime.now)
    completed_at: datetime | None = None
    is_successful: bool = False

    @property
    def state(self) -> PlanState:
        return self.state_tracker.current_state

    def transition_to(self, new_state: PlanState) -> bool:
        """Transition plan to new state."""
        return self.state_tracker.transition_to(new_state)

    def add_step(self, step: DesktopStep) -> None:
        """Add a step to the plan."""
        self.steps.append(step)

    def get_pending_steps(self) -> list[DesktopStep]:
        """Get all pending steps."""
        return [s for s in self.steps if s.status == StepStatus.PENDING]

    def get_step_by_id(self, step_id: str) -> DesktopStep | None:
        """Get step by ID."""
        for s in self.steps:
            if s.step_id == step_id:
                return s
        return None

    def to_dict(self) -> dict[str, Any]:
        return {
            "plan_id": self.plan_id,
            "goal": self.goal.to_dict(),
            "state": self.state.value,
            "steps": [s.to_dict() for s in self.steps],
            "created_at": self.created_at.isoformat(),
            "completed_at": (
                self.completed_at.isoformat() if self.completed_at else None
            ),
            "is_successful": self.is_successful,
            "total_steps": len(self.steps),
        }
