"""
Desktop Plan Representation
Constructed execution graph containing steps, dependencies, and execution state.
"""

from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional
from datetime import datetime

from .desktop_goal import DesktopGoal
from .desktop_step import DesktopStep, StepStatus, StepType


@dataclass
class DesktopPlan:
    """
    Execution plan generated by DesktopPlanner.
    """
    plan_id: str
    goal: DesktopGoal
    steps: List[DesktopStep] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.now)
    completed_at: Optional[datetime] = None
    is_successful: bool = False

    def add_step(self, step: DesktopStep) -> None:
        """Add a step to the plan."""
        self.steps.append(step)

    def get_pending_steps(self) -> List[DesktopStep]:
        """Get all pending steps."""
        return [s for s in self.steps if s.status == StepStatus.PENDING]

    def get_step_by_id(self, step_id: str) -> Optional[DesktopStep]:
        """Get step by ID."""
        for s in self.steps:
            if s.step_id == step_id:
                return s
        return None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "plan_id": self.plan_id,
            "goal": self.goal.to_dict(),
            "steps": [s.to_dict() for s in self.steps],
            "created_at": self.created_at.isoformat(),
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "is_successful": self.is_successful,
            "total_steps": len(self.steps),
        }
